apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echogame-ingress
  namespace: healthview-echogame
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - echogame.mlthrive.com
        - api-echogame.mlthrive.com
      secretName: echogame-mlthrive-tls

  rules:
    - host: echogame.mlthrive.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echogame-frontend-service
                port:
                  number: 80

    - host: api-echogame.mlthrive.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echogame-backend-service
                port:
                  number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: echogame-cdn-external
  namespace: healthview-echogame
spec:
  type: ExternalName
  externalName: 6ftru.upcloudobjects.com
  ports:
    - name: https
      port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echogame-cdn-ingress
  namespace: healthview-echogame
  annotations:
    argocd.argoproj.io/tracking-id: healthview-echogame:networking.k8s.io/Ingress:healthview-echogame/echogame-cdn-ingress
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "6ftru.upcloudobjects.com"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /echogame-media/$1
spec:
  ingressClassName: nginx
  rules:
  - host: cdn.echogame.mlthrive.com
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: echogame-cdn-external
            port:
              number: 443
  tls:
  - hosts:
    - cdn.echogame.mlthrive.com
    secretName: echogame-cdn-mlthrive-tls
